# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/alexandretk/Desktop/prova/prova/prova.cache/wt [current_project]
set_property parent.project_path C:/Users/alexandretk/Desktop/prova/prova/prova.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/alexandretk/Desktop/prova/prova/prova.srcs/sources_1/new/cmp.vhd
  C:/Users/alexandretk/Desktop/prova/prova/prova.srcs/sources_1/new/contador8.vhd
  C:/Users/alexandretk/Desktop/prova/prova/prova.srcs/sources_1/new/fsm.vhd
  C:/Users/alexandretk/Desktop/prova/prova/prova.srcs/sources_1/new/operacional.vhd
  C:/Users/alexandretk/Desktop/prova/prova/prova.srcs/sources_1/new/toplevel.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top toplevel -part xc7a35tcpg236-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
